trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: Thivagar007.HTS-L2-CS002
      trigger: true   # auto-run CD after CI

variables:
  - group: kv-secrets             # StorageAccountSasToken, PrimaryVmPassword
  - group: deployment-settings    # storageAccountName, storageContainer, blobPrefix, artifactName, PrimaryVmIp, PrimaryVmUser

pool:
  name: my-agent-2

stages:
- stage: DeployToPrimary
  displayName: "Deploy App to Primary VM"
  jobs:
  - job: UploadAndRun
    displayName: "Run startup.sh on Primary VM"
    steps:
    - checkout: self   # <-- pulls startup.sh from this repo

    - task: Bash@3
      displayName: "Install SSH tools"
      inputs:
        targetType: 'inline'
        script: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

    - task: Bash@3
      displayName: "Run startup.sh via SSH"
      inputs:
        targetType: 'inline'
        script: |
          set -euo pipefail
          test -f scripts/startup.sh || { echo "scripts/startup.sh not found"; exit 1; }
          chmod +x scripts/startup.sh

          echo "Connecting to $(PrimaryVmUser)@$(PrimaryVmIp)"
          sshpass -p "$(PrimaryVmPassword)" \
            ssh -o StrictHostKeyChecking=no "$(PrimaryVmUser)@$(PrimaryVmIp)" \
            "bash -s" -- \
            "$(StorageAccountSasToken)" \
            "$(storageAccountName)" \
            "$(storageContainer)" \
            "$(blobPrefix)" \
            "$(artifactName)" < scripts/startup.sh
